name: Yetis Test

on:
  push:
    branches:
      - '*'

jobs:
  tests_without_iptables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run Go tests
        run: make test_skip_iptables

  tests_with_iptables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run tests requiring iptables
        run: make test_only_iptables